### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by aterreno** [fix-macosx/net-monitor#2]
I've got this running on my mac os, now few things stopped working:
- certificates (When downloading gems, npm packages, boot2docker images..)
- localhost (when starting servers locally)

**Comment by aterreno** [comment]
Did a bit of unload pllist and renaming stuff and worked .. 

Really obscure (as I installed it about a week ago..) maybe you guys should warn the user that localhost traffic won't work any longer and that attempting to kill sslsplit without rolling back pf.conf will result in https traffic not working any longer.. 

my 2 cents, cheers

**Comment by landonf** [comment]
Howdy --

If you happen to have the steps you took handy and feel like writing them up as a patch for the README, I'd love to include them.

Since Net-Monitor is fairly invasive and sits in an extremely privileged position once installed, we currently include this warning in the [README](https://github.com/fix-macosx/net-monitor/tree/9587f9316e6c9e2b1b41abe83450fc129bb34299#caveats):

> NM is intended to be used on a dedicated VM or research installation; it overrides default configuration files and interposes itself in TLS network communications, and is _not_ currently recommended for day-to-day use.

Thanks!

**Comment by aterreno** [comment]
Sure, I'll fork the project and write something on the readme

**Comment by aterreno** [comment]
just made a pull request, it's not much but for a novice it might help.
